/**
 * PSYBUS — the typed bidirectional protocol for the PSY family.
 * See docs/PSYBUS.md for the full spec.
 *
 * Scope 1 ships tier 0 (in-process). The types are transport-agnostic and
 * will flow over Worker postMessage (tier 1) and WebRTC (tier 2/3) unchanged.
 */

// ── Branded nominal types (no accidental string mixing) ──────────────────────
export type DeviceId = string & { __brand: 'DeviceId' }
export type TrackId = string & { __brand: 'TrackId' }
export type SceneId = string & { __brand: 'SceneId' }
export type ParamId = string & { __brand: 'ParamId' }
export type ChokeGroupId = string & { __brand: 'ChokeGroupId' }

export const deviceId = (s: string) => s as DeviceId
export const trackId = (s: string) => s as TrackId
export const sceneId = (s: string) => s as SceneId
export const paramId = (s: string) => s as ParamId
export const chokeGroupId = (s: string) => s as ChokeGroupId

// ── Musical primitives ───────────────────────────────────────────────────────
export type MusicalKey =
  | 'C' | 'C#' | 'D' | 'D#' | 'E' | 'F' | 'F#' | 'G' | 'G#' | 'A' | 'A#' | 'B'
export type Scale = 'minor' | 'minorPentatonic' | 'phrygian' | 'harmonicMinor' | 'dorian'
export type Section = 'intro' | 'build' | 'drop' | 'breakdown' | 'outro'

export interface MusicalContext {
  key: MusicalKey
  scale: Scale
  energy: number // 0..1
  section: Section
}

// ── Provenance (the non-negotiable gate) ─────────────────────────────────────
export type License =
  | 'CC0'
  | 'CC-BY'
  | 'CC-BY-SA'
  | 'CC-BY-NC'
  | 'commercial-licensed'
  | 'psboss-dsp' // procedural sound generated by PSYBOSS itself

export interface Provenance {
  license: License
  source: string // URL or "PSYBOSS DSP generator v1"
  author?: string
  verifiedAt: number // epoch ms
  fingerprint: string // sha-256 (or 'dsp:<generator>:<seed>' for procedural)
}

export interface SampleRef {
  id: string
  provenance: Provenance // REQUIRED — host refuses to route without it
}

// ── Device capabilities ──────────────────────────────────────────────────────
export interface DeviceCapabilities {
  audio: boolean
  midiIn: boolean
  midiOut: boolean
  maxVoices: number
  params: ParamId[]
}

// ── The payload discriminated union ──────────────────────────────────────────
export type BusPayload =
  // Transport (host → devices, sample-accurate)
  | { kind: 'transport'; bpm: number; beat: number; bar: number; phase: number; playing: boolean; audioTime: number }
  | { kind: 'transport.seek'; beat: number }
  | { kind: 'transport.start' }
  | { kind: 'transport.stop' }

  // Musical context (host → devices)
  | { kind: 'context'; key: MusicalKey; scale: Scale; energy: number; section: Section }

  // Note / trigger events (host OR device → devices)
  | { kind: 'note'; track: TrackId; note: number; vel: number; durBeats: number; channel: number }
  | { kind: 'note.off'; track: TrackId; note: number }
  | { kind: 'trig'; track: TrackId; scene: SceneId; sampleRef?: SampleRef }

  // Device-to-device control (the NEW capability the family lacked)
  | { kind: 'sidechain.duck'; target: TrackId; depth: number; releaseMs: number }
  | { kind: 'choke'; group: ChokeGroupId; except?: DeviceId }
  | { kind: 'param.lock'; track: TrackId; step: number; param: ParamId; value: number }
  | { kind: 'param.set'; track: TrackId; param: ParamId; value: number }

  // Telemetry / health (device → host)
  | { kind: 'latency'; device: DeviceId; reportLatencyMs: number }
  | { kind: 'voice.count'; device: DeviceId; active: number; stolen: number }
  | { kind: 'error'; device: DeviceId; code: string; message: string }

// ── The envelope ─────────────────────────────────────────────────────────────
export interface BusEnvelope<T extends BusPayload = BusPayload> {
  rev: number // monotonic transport revision (ticks since start)
  seed: number // deterministic seed for this performance
  src: DeviceId // publisher
  dst: DeviceId | 'broadcast' // target or all
  ts: number // audio-context time (seconds) the event is valid at
  payload: T
}

export type Unsubscribe = () => void
export type BusFilter = (p: BusPayload) => boolean
export type BusHandler = (e: BusEnvelope) => void

// ── The host interface ───────────────────────────────────────────────────────
export interface PsyBus {
  subscribe(device: DeviceId, filter: BusFilter, handler: BusHandler): Unsubscribe
  publish(envelope: BusEnvelope): void
  register(device: DeviceId, capabilities: DeviceCapabilities): void
  unregister(device: DeviceId): void
  assertProvenance(ref: SampleRef): void
  nextRev(): number
  seed(): number
}
